<?php

/**
 * My Application bootstrap file.
 */
use Nette\Application\Routers\Route;
use Nette\Utils\Strings;
use Nette\Application\Routers\SimpleRouter;

// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE); 
$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
        ->addDirectory(APP_DIR)
        ->addDirectory(LIBS_DIR)
        ->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();

Route::addStyle('titleProduct');
Route::setStyleProperty('titleProduct', Route::FILTER_OUT, function($url) {
            return Strings::webalize($url);
        });

Route::setStyleProperty('titleProduct', Route::FILTER_IN, function($url) {
            return Strings::webalize($url);
        });

Route::addStyle('titleCategory', 'titleProduct'); // dědí masku titleProduct

if (
    function_exists('apache_get_modules') && in_array('mod_rewrite', apache_get_modules()) // pro Apache
    || isset($_SERVER["NETTE_HTACCESS"]) // pro FastCGI nebo okoliv jineho kde mame flag
) {
// Admin base router
    $container->router[] = new Route('admin[/<presenter>[/<action>[/<id>]]]?strana=<paginator-page>', array(
                'module' => "admin",
                'presenter' => array(
                    Route::VALUE => 'Homepage',
                    Route::FILTER_TABLE => array(
                        // řetězec v URL => presenter
                        'uvod' => 'Homepage',
                        'produkt' => 'Product',
                        'objednavka' => 'Order',
                        'kategorie' => 'Category',
                        'uzivatel' => 'User',
                        'nastaveni' => 'Setting',
                        'vzhled' => 'Image',
                    ),
                ),
                'action' => array(
                    Route::VALUE => 'default',
                    Route::FILTER_TABLE => array(
                        // řetězec v URL => akce
                        'ukaz' => 'show',
                        'upravit' => 'edit'
                    ),
                ),
                'id' => NULL,
            ));

    $container->router[] = new Route('admin/produkt/<id>', array(
                'module' => "admin",
                'presenter' => 'Product',
                'action' => 'default'
            ));

    $container->router[] = new Route('admin/objednavka/<id>', array(
                'module' => "admin",
                'presenter' => 'Order',
                'action' => 'default'
            ));


// Setup router
    $container->router[] = new Route('index.php', array(
                'presenter' => 'Homepage',
                'action' => 'default',
                    ), Route::ONE_WAY);

    $container->router[] = new Route('kategorie/<id>-<titleCategory>', array(
                'presenter' => 'Category',
                'action' => 'default'
            ));

    $container->router[] = new Route('produkt/<id>-<titleProduct>', array(
                'presenter' => 'Product',
                'action' => 'default'
            ));

    $container->router[] = new Route('[<presenter>[/<action>[/<id>]]]?strana=<paginator-page> ', array(
                'presenter' => array(
                    Route::VALUE => 'Homepage',
                    Route::FILTER_TABLE => array(
                        // řetězec v URL => presenter
                        'produkt' => 'Product',
                        'kosik' => 'Basket',
                        'kategorie' => 'Category',
                        'objednavka' => 'Order',
                        'prihlaseni' => 'Login',
                        'registrace' => 'Registration',
                        'vyhledavani' => 'Search',
                        'klient' => 'Client',
                    ),
                ),
                'action' => array(
                    Route::VALUE => 'default',
                    Route::FILTER_TABLE => array(
                        // řetězec v URL => akce
                        'platba-doprava' => 'paymentDelivery',
                        'shrnuti' => 'summary',
                        'dokonceni' => 'complete',
                        'obchodni-podminky' => 'tradeTerms',
                        'napiste-nam' => 'tellUs',
                        'kontakt' => 'contact',
                        'novinky' => 'news',
                        'obnoveni-hesla' => 'passwordRecovery',
                        'muj-ucet' => 'myAccount',
                        'me-objednavky' => 'myOrders',
                    ),
                ),
                'id' => NULL,
            ));
} else {
   $container->router[] = new SimpleRouter('Homepage:default');
}

// Configure and run the application!
$container->application->run();